services:
  - type: web
    name: bulk-ordering-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://bulk-ordering-platform-myx5.onrender.com
